import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import WalletProvider from "@/providers/provider";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WalletProvider>
        <body className={manrope.className}>{children}</body>
      </WalletProvider>
    </html>
  );
}
